version: '3.8'

volumes:
  postgres-data:

    null
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.16
        NODE_VERSION: "none"
    env_file:
      - .env
    volumes:
      - ..:/home/app:cached
    command: sleep infinity

  db:
    image: postgres:9.4
    restart: unless-stopped
    tty: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    env_file:
      - .env
    ports:
      - "9000:80"
    depends_on:
      - db